"use client";

import { useState, useCallback } from "react";
import type { TranscriptEntry } from "@/components/transcript";
import type { SearchActivity } from "@/components/search-results";

interface ExportSummaryProps {
  transcript: TranscriptEntry[];
  searchActivities: SearchActivity[];
  personaName: string;
  topic?: string;
  accentColor?: string;
}

const ACCENT_HOVER: Record<string, string> = {
  emerald: "hover:bg-emerald-500/10 hover:text-emerald-400",
  red: "hover:bg-red-500/10 hover:text-red-400",
  violet: "hover:bg-violet-500/10 hover:text-violet-400",
};

const ACCENT_TOAST: Record<string, string> = {
  emerald: "bg-emerald-500/10 text-emerald-300 border-emerald-500/20",
  red: "bg-red-500/10 text-red-300 border-red-500/20",
  violet: "bg-violet-500/10 text-violet-300 border-violet-500/20",
};

function generateMarkdown(
  transcript: TranscriptEntry[],
  searchActivities: SearchActivity[],
  personaName: string,
  topic?: string
): string {
  const date = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const lines: string[] = [];
  lines.push(`# Conversation with ${personaName}`);
  if (topic) lines.push(`**Topic:** ${topic}`);
  lines.push(`**Date:** ${date}`);
  lines.push("");

  if (transcript.length > 0) {
    lines.push("## Transcript");
    lines.push("");
    for (const entry of transcript) {
      const speaker = entry.role === "user" ? "You" : personaName;
      lines.push(`**${speaker}:** ${entry.text}`);
      lines.push("");
    }
  }

  const completedSearches = searchActivities.filter(
    (a) => a.status === "complete" && a.results && a.results.length > 0
  );

  if (completedSearches.length > 0) {
    lines.push("## Sources");
    lines.push("");
    const seen = new Set<string>();
    for (const activity of completedSearches) {
      for (const result of activity.results ?? []) {
        if (result.url && !seen.has(result.url)) {
          seen.add(result.url);
          const title = result.title || result.url;
          const toolLabel = activity.tool_name.replace("search_", "");
          lines.push(
            `- [${title}](${result.url}) — *${toolLabel} search for "${activity.query}"*`
          );
        }
      }
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by AI Avatar Studio*");

  return lines.join("\n");
}

function downloadMarkdown(content: string, personaName: string) {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${personaName.toLowerCase().replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ExportSummary({
  transcript,
  searchActivities,
  personaName,
  topic,
  accentColor,
}: ExportSummaryProps) {
  const [feedback, setFeedback] = useState<"copied" | "downloaded" | null>(
    null
  );
  const [showMenu, setShowMenu] = useState(false);

  const hoverClass = accentColor
    ? ACCENT_HOVER[accentColor] ?? "hover:bg-white/[0.04] hover:text-white/60"
    : "hover:bg-white/[0.04] hover:text-white/60";

  const toastClass = accentColor
    ? ACCENT_TOAST[accentColor] ?? "bg-[--surface-2] text-[--text-primary] border-[--border-subtle]"
    : "bg-[--surface-2] text-[--text-primary] border-[--border-subtle]";

  const isEmpty = transcript.length === 0 && searchActivities.length === 0;

  const handleCopy = useCallback(async () => {
    const md = generateMarkdown(
      transcript,
      searchActivities,
      personaName,
      topic
    );
    await navigator.clipboard.writeText(md);
    setFeedback("copied");
    setShowMenu(false);
    setTimeout(() => setFeedback(null), 2000);
  }, [transcript, searchActivities, personaName, topic]);

  const handleDownload = useCallback(() => {
    const md = generateMarkdown(
      transcript,
      searchActivities,
      personaName,
      topic
    );
    downloadMarkdown(md, personaName);
    setFeedback("downloaded");
    setShowMenu(false);
    setTimeout(() => setFeedback(null), 2000);
  }, [transcript, searchActivities, personaName, topic]);

  return (
    <div className="relative">
      <button
        onClick={() => (isEmpty ? null : setShowMenu((v) => !v))}
        disabled={isEmpty}
        title={isEmpty ? "Start a conversation first" : "Export summary"}
        className={`relative rounded-md p-1.5 text-[--text-quaternary] transition-all duration-200 disabled:opacity-25 disabled:cursor-not-allowed ${hoverClass}`}
      >
        <svg
          width="15"
          height="15"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
          <polyline points="14 2 14 8 20 8" />
          <line x1="12" y1="18" x2="12" y2="12" />
          <polyline points="9 15 12 18 15 15" />
        </svg>
      </button>

      {/* Dropdown menu */}
      {showMenu && (
        <>
          <div
            className="fixed inset-0 z-40"
            onClick={() => setShowMenu(false)}
          />
          <div className="absolute right-0 top-full mt-1.5 z-50 w-48 rounded-md border border-[--border-default] bg-[--surface-1] backdrop-blur-xl shadow-2xl shadow-black/50 overflow-hidden">
            <button
              onClick={handleCopy}
              className="flex w-full items-center gap-2.5 px-3.5 py-2.5 text-xs text-[--text-secondary] hover:bg-white/[0.04] hover:text-white transition-colors"
            >
              <svg
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
              >
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
              </svg>
              Copy as Markdown
            </button>
            <div className="h-px bg-[--border-subtle] mx-2" />
            <button
              onClick={handleDownload}
              className="flex w-full items-center gap-2.5 px-3.5 py-2.5 text-xs text-[--text-secondary] hover:bg-white/[0.04] hover:text-white transition-colors"
            >
              <svg
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
              >
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Download .md file
            </button>
          </div>
        </>
      )}

      {/* Toast feedback */}
      {feedback && (
        <div
          className={`absolute right-0 top-full mt-1.5 z-50 whitespace-nowrap rounded-md border px-3 py-1.5 text-[11px] font-mono font-medium shadow-lg ${toastClass}`}
          style={{
            animation: "fade-slide-in 200ms ease-out forwards",
          }}
        >
          {feedback === "copied" ? "Copied to clipboard" : "Downloaded"}
        </div>
      )}
    </div>
  );
}
